version: 2.1

executors:
  gcp-default:
    description: A debian-based machine executor
    machine: true

orbs:
  gcp-gcr: fresh8gaming/google-artifact-orb@1.0.1
  slack: circleci/slack@3.4.2
  docker: circleci/docker@1.5.0

jobs:
  test-and-lint:
    docker:
      - image: cimg/go:1.17
    steps:
      - checkout
      - run: make install-tools
      - run: make test
      - run: make lint

  build-and-push-image:
    executor: gcp-default
    parameters:
      docker-context:
        default: .
        description: >
          Path to the directory containing your build context, defaults to .
          (working directory)
        type: string
      dockerfile:
        default: Dockerfile
        description: "Name of dockerfile to use, defaults to Dockerfile"
        type: string
      extra_build_args:
        default: ""
        description: >
          Extra flags to pass to docker build. For examples, see
          https://docs.docker.com/engine/reference/commandline/build
        type: string
      image:
        description: A name for your Docker image
        type: string
      path:
        default: .
        description: >
          Path to the directory containing your Dockerfile, defaults to . (working
          directory)
        type: string
      registry-url:
        default: europe-docker.pkg.dev
        description: The GAR URL
        type: string
      registry-name:
        default: main
        description: The GAR name
        type: string
      tag:
        default: latest
        description: A Docker image tag
        type: string
    steps:
      - checkout
      - gcp-gcr/gcr-auth:
          gcloud-service-key: <<parameters.GCLOUD_SERVICE_KEY>>
          google-compute-zone: <<parameters.GOOGLE_COMPUTE_ZONE>>
          google-project-id: <<parameters.GOOGLE_PROJECT_ID>>
          registry-url: <<parameters.registry-url>>
      - gcp-gcr/build-image:
          docker-context: <<parameters.docker-context>>
          dockerfile: <<parameters.dockerfile>>
          extra_build_args: <<parameters.extra_build_args>>
          google-project-id: <<parameters.GOOGLE_PROJECT_ID>>
          image: <<parameters.image>>
          path: <<parameters.path>>
          registry-url: <<parameters.registry-url>>
          registry-name: <<parameters.registry-name>>
          tag: <<parameters.tag>>
          workspace-root: .
      - gcp-gcr/push-image:
          google-project-id: <<parameters.GOOGLE_PROJECT_ID>>
          image: <<parameters.image>>
          registry-url: <<parameters.registry-url>>
          registry-name: <<parameters.registry-name>>
          tag: ${CIRCLE_SHA1}
      - gcp-gcr/tag-image:
          google-project-id: <<parameters.GOOGLE_PROJECT_ID>>
          image: <<parameters.image>>
          registry-url: <<parameters.registry-url>>
          registry-name: <<parameters.registry-name>>
          source-tag: <<parameters.tag>>
          target-tag: latest
      - run: mkdir /tmp/workspace
      - run: echo "-p <<parameters.image>>.docker.tag=$CIRCLE_SHA1" > /tmp/workspace/<<parameters.image>>
      - run: cat /tmp/workspace/<<parameters.image>>
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - <<parameters.image>>

  concat-versions:
    docker:
      - image: cimg/base:2020.01
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: cat /tmp/workspace/* | tr "\n" " " > /tmp/workspace/merged-versions
      - run: cat /tmp/workspace/merged-versions
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - merged-versions

  update-argo:
    docker:
      - image: cimg/base:2020.01
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: "Fetch argocd cli"
          command: "curl -sSL -o ./argocd https://${ARGOCD_SERVER}/download/argocd-linux-amd64 && chmod +x ./argocd"
      - run:
          name: "Set Image Tag"
          command: "./argocd app set {{ $.Name }} $(cat /tmp/workspace/merged-versions) --grpc-web --auth-token=$ARGO_AUTH_TOKEN"
      - run:
          name: "Sync"
          command: "./argocd app sync {{ $.Name }} --grpc-web --auth-token=$ARGO_AUTH_TOKEN"

workflows:
  version: 2
  main:
    jobs:
      - test-and-lint
      - docker/hadolint:
          dockerfiles: "build/Dockerfile"
{{range .Services -}}
{{if .CIEnabled}}
      - build-and-push-image:
          name: build-and-push-{{ .Name }}
          image: {{ $.Name }}-{{ .Name }}
          extra_build_args: "--build-arg APP={{ .Name }}"
          dockerfile: build/Dockerfile
          context:
            - artifact-registry
          requires:
            - test-and-lint
            - docker/hadolint
{{end}}
{{- end}}
      - concat-versions:
          requires:
{{range .Services -}}
{{if .CIEnabled}}
            - build-and-push-{{ .Name }}
{{end}}
{{- end}}
      - update-argo:
          context:
            - argo
          requires:
            - concat-versions
          filters:
            branches:
              only:
                - trunk
