version: 2.1

executors:
  gcp-default:
    description: A debian-based machine executor
    machine:
      image: ubuntu-2004:202010-01

references:
  workspace_root: &workspace_root /tmp/workspace

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

orbs:
  gcp-gcr: circleci/gcp-gcr@0.14.1
  slack: circleci/slack@3.4.2
  docker: circleci/docker@2.0.3
  whitesource-scan: whitesource/whitesource-scan@21.6.3
  compare-url: iynere/compare-url@1.2.0

jobs:
  test-and-lint:
    docker:
      - image: cimg/go:1.18
    steps:
      - checkout
      {{- if not .SkipInstallTools}}
      - run: make install-tools
      {{end}}
      - run: make test
      - run: make lint

  buf-lint:
    docker:
      - image: cimg/go:1.18
    steps:
      - checkout
      - run: make install-tools
      - run: make buf-lint

  build-and-push-image:
    executor: gcp-default
    parameters:
      extra_build_args:
        default: ""
        description: >
          Extra flags to pass to docker build. For examples, see
          https://docs.docker.com/engine/reference/commandline/build
        type: string
      image:
        description: A name for your Docker image
        type: string
      path:
        default: .
        description: >
          Path to the directory containing your Dockerfile, defaults to . (working
          directory)
        type: string
      registry-url:
        default: europe-docker.pkg.dev
        description: The GAR URL
        type: string
      registry-name:
        default: main
        description: the GAR name
        type: string
      service_name:
        description: Name of the service
        type: string
      tag:
        default: latest
        description: A Docker image tag
        type: string
    steps:
      - checkout
      - gcp-gcr/gcr-auth:
          gcloud-service-key: GCLOUD_SERVICE_KEY
          google-compute-zone: GOOGLE_COMPUTE_ZONE
          google-project-id: GOOGLE_PROJECT_ID
          registry-url: <<parameters.registry-url>>
      - gcp-gcr/build-image:
          docker-context: .
          dockerfile: build/Dockerfile
          google-project-id: GOOGLE_PROJECT_ID
          extra_build_args: <<parameters.extra_build_args>>
          image: <<parameters.registry-name>>/<<parameters.image>>
          path: <<parameters.path>>
          registry-url: <<parameters.registry-url>>
          tag: <<parameters.tag>>
          workspace-root: .
      - gcp-gcr/push-image:
          google-project-id: GOOGLE_PROJECT_ID
          image: <<parameters.registry-name>>/<<parameters.image>>
          registry-url: <<parameters.registry-url>>
          tag: ${CIRCLE_SHA1}
      - gcp-gcr/tag-image:
          google-project-id: GOOGLE_PROJECT_ID
          image: <<parameters.registry-name>>/<<parameters.image>>
          registry-url: <<parameters.registry-url>>
          source-tag: <<parameters.tag>>
          target-tag: latest
      - run: mkdir /tmp/workspace
      - run: echo "-p <<parameters.service_name>>.docker.tag=$CIRCLE_SHA1" > /tmp/workspace/<<parameters.image>>
      - run: cat /tmp/workspace/<<parameters.image>>
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - <<parameters.image>>

  concat-versions:
    docker:
      - image: cimg/base:2020.01
    steps:
      - *attach_workspace
      - run: cat /tmp/workspace/* | tr "\n" " " > /tmp/workspace/merged-versions
      - run: cat /tmp/workspace/merged-versions
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - merged-versions

  update-argo:
    parameters:
      argo-cd-project:
        type: string
    docker:
      - image: cimg/base:2021.10
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: "Fetch argocd cli"
          command: "curl -sSL -o ./argocd https://${ARGOCD_SERVER}/download/argocd-linux-amd64 && chmod +x ./argocd"
      - run:
          name: "Set Image Tag"
          command: |
            for project in <<parameters.argo-cd-project>>; do
              ./argocd app set $project $(cat /tmp/workspace/merged-versions) --grpc-web --auth-token=$ARGO_AUTH_TOKEN
            done
      - run:
          name: "Sync"
          command: "./argocd app sync <<parameters.argo-cd-project>> --grpc-web --auth-token=$ARGO_AUTH_TOKEN"

  kube-score:
    parameters:
      version:
        type: string
        default: 1.14.0
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: 
          name: Download helm to template charts
          command: "curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 && chmod 700 get_helm.sh && ./get_helm.sh"
      - run:
          name: Download kube-score
          command:  "curl -sSL -o ./kube-score https://github.com/zegl/kube-score/releases/download/v<<parameters.version>>/kube-score_<<parameters.version>>_linux_amd64 && chmod +x ./kube-score"
      - run:
          name: Scan charts
          command: "cat ./deploy/chart/values-production/*.yaml > ./values-production.yaml && helm template -n {{ .Name }} {{ .Name }} --values ./deploy/chart/values.yaml --values ./values-production.yaml ./deploy/chart |./kube-score score --ignore-test container-image-tag --ignore-test horizontalpodautoscaler-has-target - || true"

workflows:
  version: 2
{{- if .WhitesourceEnabled}}
  whitesource:
    jobs:
      - whitesource-scan/scan:
          config_file_path: .circleci/.whitesource
          commands_file_path: .circleci/.whitesource_setup.sh
          context:
            - whitesource
            - whitesource-{{ .Team }}
            - go118
{{- end}}
  main:
    jobs:
      - test-and-lint
{{if $.HasGRPC}}
      - buf-lint
{{- end}}
{{if $.KubescoreEnabled}}
      - kube-score
{{- end}}
      - docker/hadolint:
          dockerfiles: "build/Dockerfile"
          hadolint-tag: 2.9.3-debian
      - approve-trigger-all-builds:
          type: approval
          filters:
            branches:
              only:
                - trunk
          requires:
            - test-and-lint
{{if $.HasGRPC}}
            - buf-lint
{{- end}}
            - docker/hadolint

{{range .ChangedServices -}}
  {{if .CIEnabled}}
      - build-and-push-image:
          name: build-and-push-{{ .Name }}
          image: {{ $.Name }}-{{ .Name }}
          service_name: {{ .NameUnderscored }}
          tag: ${CIRCLE_SHA1}
          extra_build_args: "--build-arg APP={{ .Name }}"
          context:
            - artifact-registry
          requires:
            - test-and-lint
    {{if $.HasGRPC}}
            - buf-lint
    {{- end}}
            - docker/hadolint
  {{end}}
{{- end}}

{{ if $.NeedsApproval }}
      - approve-production:
          type: approval
          filters:
            branches:
              only:
                - trunk
  {{- if .Staging }}
      - approve-staging:
          type: approval
          filters:
            branches:
              only:
                - trunk
  {{ end }}
{{ end }}



{{range .Services -}}
  {{if .CIEnabled}}
      - build-and-push-image:
          name: all-builds-build-and-push-{{ .Name }}
          image: {{ $.Name }}-{{ .Name }}
          service_name: {{ .NameUnderscored }}
          tag: ${CIRCLE_SHA1}
          extra_build_args: "--build-arg APP={{ .Name }}"
          context:
            - artifact-registry
          requires:
            - approve-trigger-all-builds
  {{end}}
{{- end}}
      - concat-versions:
          name: concat-versions-all-builds
          requires:
{{range .Services -}}
  {{if .CIEnabled}}
            - all-builds-build-and-push-{{ .Name }}
  {{end}}
{{- end}}
      - approve-all-builds-production:
          type: approval
          filters:
            branches:
              only:
                - trunk

      - update-argo:
          name: update-argo-all-builds-production
          argo-cd-project: {{if .ArgoAppNamesProduction }}{{ .ArgoAppNamesProduction }}{{else}}{{.Name}}{{end}}
          context:
            - argo
          requires:
            - concat-versions-all-builds
{{ if .Staging}}
            - update-argo-all-builds-staging
            - approve-all-builds-production

{{end}}

{{ if .Staging}}
      - approve-all-builds-staging:
          type: approval
          filters:
            branches:
              only:
                - trunk

      - update-argo:
          name: update-argo-all-builds-staging
          argo-cd-project: {{if .ArgoAppNamesProduction }}{{ .ArgoAppNamesProduction }}{{else}}{{.Name}}{{end}}
          context:
            - argo
          requires:
            - concat-versions-all-builds
            - approve-all-builds-staging
{{end}}